In [5]:
import requests
import pandas as pd

url = "https://dogapi.dog/api/v2/breeds"
response = requests.get(url)

data = response.json()

clean_data = []

for breed in data["data"]:
    attr = breed.get("attributes", {})

    clean_data.append({
        "name": attr.get("name", None),
        "description": attr.get("description", None),
        "life_span": str(attr.get("life", None))  # convert to string if it's nested
    })

df = pd.DataFrame(clean_data)

# Basic cleaning
df.drop_duplicates(inplace=True)
df.fillna("Unknown", inplace=True)

df.head()

,name,description,life_span
0,Affenpinscher,The Affenpinscher is a small and playful breed...,"{'max': 16, 'min': 14}"
1,Afghan Hound,The Afghan Hound is a large and elegant breed ...,"{'max': 14, 'min': 12}"
2,Airedale Terrier,The Airedale Terrier is a large and powerful b...,"{'max': 14, 'min': 12}"
3,Akita,"The Akita is a large, muscular dog breed that ...","{'max': 12, 'min': 10}"
4,Alaskan Klee Kai,The Alaskan Klee Kai is a small to medium-size...,"{'max': 15, 'min': 12}"

In [10]:
from sqlalchemy import create_engine

username = "postgres"
password = "libertycity"
host = "localhost"
port = "5432"
database = "dogs_db"

engine = create_engine(f"postgresql://{username}:{password}@{host}:{port}/{database}")

In [7]:
!pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 287.2 kB/s eta 0:00:08
   ----------- ---------------------------- 0.8/2.8 MB 451.5 kB/s eta 0:00:05
   ----------- ---------------------------- 0.8/2.8 MB 451.5 kB/s eta 0:00:05
   --------------- ------------------------ 1.0/2.8 MB 486.2 kB/s eta 0:00:04
   --------------- ------------------------ 1.0/2.8 MB 486.2 kB/s eta 0:00:04
   ------------------- -------------------- 1.3/2.8 MB 510.3 kB/s eta 0:00:03
   ------------------- -------------------- 1.3/2.8 MB 510.3 kB/s eta 0:00:03
   ------------------- -------------------- 1.3/2.8 MB 510.3 kB/s eta 0:00:03
   ---------------------- ----------------- 1.6/2.8 MB 524.0 kB/s eta 0:00:03
   ---------------------- ----------------- 1.6/2.8 MB 524.0 kB/s eta 0:00:03
   -------------------------- ------------- 1.8/2.8 MB 535.9 kB/s eta 0:00:02
   -------------------------- ------------- 1.8/2.8 MB 535.9 kB/s eta 0:00:02
   ------------------------------ --------- 2.1/2.8 MB 543.6 kB/s eta 0:00:02
   ------------------------------ --------- 2.1/2.8 MB 543.6 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 546.6 kB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 546.6 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.8 MB 549.5 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.8 MB 549.5 kB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 530.5 kB/s  0:00:05
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [9]:
df.to_sql(
    name="dog_breeds",
    con=engine,
    if_exists="replace",  # use "append" later
    index=False
)

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "dogs_db" does not exist

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [11]:
engine = create_engine("postgresql://postgres:libertycity@localhost:5432/dogs_db")

In [12]:
df.to_sql(
    name="dog_breeds",
    con=engine,
    if_exists="replace",  # use "append" later
    index=False
)

283

In [14]:
import pandas as pd

pd.read_sql("SELECT * FROM dog_breeds LIMIT 10;", engine)

,name,description,life_span
0,Affenpinscher,The Affenpinscher is a small and playful breed...,"{'max': 16, 'min': 14}"
1,Afghan Hound,The Afghan Hound is a large and elegant breed ...,"{'max': 14, 'min': 12}"
2,Airedale Terrier,The Airedale Terrier is a large and powerful b...,"{'max': 14, 'min': 12}"
3,Akita,"The Akita is a large, muscular dog breed that ...","{'max': 12, 'min': 10}"
4,Alaskan Klee Kai,The Alaskan Klee Kai is a small to medium-size...,"{'max': 15, 'min': 12}"
5,Alaskan Malamute,The Alaskan Malamute is a large and powerful s...,"{'max': 15, 'min': 12}"
6,American Bulldog,The American Bulldog is a large and powerful b...,"{'max': 14, 'min': 12}"
7,American English Coonhound,The American English Coonhound is a large and ...,"{'max': 14, 'min': 12}"
8,American Eskimo Dog,The American Eskimo Dog is a small to medium-s...,"{'max': 15, 'min': 12}"
9,American Foxhound,The American Foxhound is a large and athletic ...,"{'max': 15, 'min': 12}"