In [8]:
import requests

api_key = "b8740dd60a554754bd2796a720decf3c"

url = "https://newsapi.org/v2/everything"

params = {
    "q": "Barcelona",
    "language": "en",
    "pageSize": 10,
    "apiKey": api_key
}

response = requests.get(url, params=params)

data = response.json()

print(data)

{'status': 'ok', 'totalResults': 4728, 'articles': [{'source': {'id': None, 'name': 'MacRumors'}, 'author': 'Joe Rossignol', 'title': "Apple's Impressive Barcelona Store Reopens Next Month", 'description': "Apple's beautiful Passeig de Gràcia store in the heart of Barcelona, Spain has been temporarily closed for renovations since mid-February, but the location is finally set to reopen next month. The store will resume business on May 26, according to Apple's web…", 'url': 'https://www.macrumors.com/2026/04/06/apple-passeig-de-gracia-reopens-next-month/', 'urlToImage': 'https://images.macrumors.com/t/kauGLClSZDghitCK3UG9AdJrHS0=/2880x/article-new/2025/12/Apple-Passeig-de-Gracia.jpeg', 'publishedAt': '2026-04-06T16:46:45Z', 'content': "Apple's beautiful Passeig de Gràcia store in the heart of Barcelona, Spain has been temporarily closed for renovations since mid-February, but the location is finally set to reopen next month. The st… [+409 chars]"}, {'source': {'id': None, 'name': 'CNET'}, 'author': 'Kevin Lynch', 'title': 'Champions League Soccer: Stream Atlético Madrid vs. Barcelona Live', 'description': "Hansi Flick's team needs to overturn a two-goal deficit at the Metropolitano Stadium.", 'url': 'https://www.cnet.com/tech/services-and-software/champions-league-soccer-stream-atletico-madrid-vs-barcelona-live/', 'urlToImage': 'https://www.cnet.com/a/img/resize/8f12f38895b754ad17419d285d24ef81c55e695b/hub/2026/04/14/705508ce-dbc0-4285-b66d-0c10acad4432/gettyimages-2270878694.jpg?auto=webp&fit=crop&height=675&width=1200', 'publishedAt': '2026-04-14T16:01:17Z', 'content': 'When to watch Atlético Madrid vs. Barcelona\r\n<ul><li>Tuesday at 3 p.m. ET (12 p.m. PT).</li></ul>Where to watch\r\n<ul><li>Atlético Madrid vs. Barcelona will air in the US on Paramount Plus.</li></ul>B… [+3254 chars]'}, {'source': {'id': None, 'name': 'BBC News'}, 'author': 'Bobbie Jackson', 'title': 'Defending champion Alcaraz to miss French Open', 'description': "Two-time defending champion Carlos Alcaraz says he will miss next month's French Open with an ongoing wrist injury.", 'url': 'https://www.bbc.com/sport/tennis/articles/c15de9d91jwo', 'urlToImage': 'https://ichef.bbci.co.uk/ace/branded_sport/1200/cpsprodpb/eb7a/live/5c0f70d0-6139-11ee-ac8c-9d18dbc280ea.png', 'publishedAt': '2026-04-24T16:02:16Z', 'content': "Two-time defending champion Carlos Alcaraz says he will miss next month's French Open because of an ongoing wrist injury.\r\nThe world number two withdrew from last week's Barcelona Open after sustaini… [+576 chars]"}, {'source': {'id': None, 'name': 'BBC News'}, 'author': 'Michael Emons', 'title': "Lewandowski misses out on World Cup - who else won't be there?", 'description': 'The World Cup includes 48 nations, but there are still a number of top players who have missed out on qualification.', 'url': 'https://www.bbc.com/sport/football/articles/cn89z009kv3o', 'urlToImage': 'https://ichef.bbci.co.uk/ace/branded_sport/1200/cpsprodpb/0724/live/cd6b7140-2d45-11f1-9d06-9fd6b940097f.jpg', 'publishedAt': '2026-03-31T22:41:01Z', 'content': "One of the greatest strikers of the past 15 years - Poland's Robert Lewandowski - is among the big names who will not be playing at the 2026 World Cup in Canada, the United States and Mexico.\r\nThe 37… [+528 chars]"}, {'source': {'id': None, 'name': 'BBC News'}, 'author': 'Mike Peter', 'title': 'Former BOA and Wada executive Reedie dies aged 84', 'description': 'Sir Craig Reedie, the former chair of the British Olympic Association and president of the World Anti-Doping Agency, dies at the age of 84.', 'url': 'https://www.bbc.com/sport/olympics/articles/cp84w4pd29jo', 'urlToImage': 'https://ichef.bbci.co.uk/ace/branded_sport/1200/cpsprodpb/4311/live/a9b05320-31db-11f1-bf60-311fd3da206f.jpg', 'publishedAt': '2026-04-06T17:24:23Z', 'content': 'Sir Craig Reedie, the former chair of the British Olympic Association (BOA) and president of the World Anti-Doping Agency (Wada), has died at the age of 84.\r\nReedie chaired the BOA between 1992 and 2… [+2099 chars]'}, {'source': {'id': None, 'name': 'BBC News'}, 'author': 'Phil McNulty', 'title': "Will Iraola's departure speed up the managerial merry-go-round?", 'description': "Andoni Iraola's decision to leave Bournemouth could make it a frantic summer in the Premier League's managerial market, says chief football writer Phil McNulty.", 'url': 'https://www.bbc.com/sport/football/articles/ckgeerk761mo', 'urlToImage': 'https://ichef.bbci.co.uk/ace/branded_sport/1200/cpsprodpb/d5ef/live/553b3ba0-37f0-11f1-bf98-335695df34d3.jpg', 'publishedAt': '2026-04-14T13:05:18Z', 'content': "Manchester United co-owner Sir Jim Ratcliffe and his Old Trafford cohorts must decide whether to give Michael Carrick the manager's job on a permanent basis or look elsewhere.\r\nCarrick has guided Uni… [+3471 chars]"}, {'source': {'id': None, 'name': 'CNET'}, 'author': 'Kevin Lynch', 'title': 'Champions League Soccer: Stream Barcelona vs. Atletico Madrid Live', 'description': "Hansi Flick's team is looking to gain an advantage and head to Metropolitano Stadium next week.", 'url': 'https://www.cnet.com/tech/services-and-software/champions-league-soccer-stream-barcelona-vs-atletico-madrid-live/', 'urlToImage': 'https://www.cnet.com/a/img/resize/f266e3295ba6675f659361fd90ed99c779bd839e/hub/2026/04/07/c03088dd-208a-45f0-8619-25262671fb25/gettyimages-2269836424.jpg?auto=webp&fit=crop&height=675&width=1200', 'publishedAt': '2026-04-08T16:01:18Z', 'content': 'When to watch Barcelona vs. Atletico Madrid\r\n<ul><li>Wednesday at 3 p.m. ET (12 p.m. PT).</li></ul>Where to watch\r\n<ul><li>Barcelona vs. Atletico Madrid will air in the US on Paramount Plus.</li></ul… [+3362 chars]'}, {'source': {'id': None, 'name': 'CNET'}, 'author': 'Jeff Carlson', 'title': 'The Motorola Razr Fold Has a UK Price, but Will It Be So Expensive in the US?', 'description': 'A direct conversion from pounds to dollars would make the new two-panel folding phone pricey in the US.', 'url': 'https://www.cnet.com/tech/mobile/motorola-razr-fold-has-a-uk-price-but-will-it-be-so-expensive-in-the-us/', 'urlToImage': 'https://www.cnet.com/a/img/resize/1b406f6ad6161d7aafd3ecb1dc84152fa59124b6/hub/2026/03/01/e5051989-566d-4098-8737-f561364bbf19/img-5917.jpg?auto=webp&fit=crop&height=675&width=1200', 'publishedAt': '2026-04-23T18:05:28Z', 'content': "Motorola opened pre-orders in the UK for its upcoming\xa0Razr Fold\xa0two-panel phone, but we don't yet know what it will cost in the US. If we apply a direct currency conversion, though, it could be excep… [+1951 chars]"}, {'source': {'id': None, 'name': 'Pitchfork'}, 'author': 'Walden Green', 'title': 'Actress and Suzanne Ciani Release Collaborative Live Album', 'description': 'Concrète Waves documents two improvised sets at London’s Barbican Theatre and Barcelona’s Sónar Festival', 'url': 'https://pitchfork.com/news/actress-and-suzanne-ciani-release-collaborative-live-album/', 'urlToImage': 'https://media.pitchfork.com/photos/69c59b718463f85a48f50fd2/16:9/w_1280,c_limit/Suzanne-Ciani-Actress.jpeg', 'publishedAt': '2026-03-27T04:16:41Z', 'content': 'Last year, British electronic producer Actress and modular synthesis pioneer Suzanne Ciani performed an improvised piece titled Concrète Waves at the Barbican theatre in London and Barcelonas Sónar F… [+1301 chars]'}]}

In [9]:
articles = []

for article in data["articles"]:
    articles.append({
        "title": article["title"],
        "source": article["source"]["name"],
        "published": article["publishedAt"],
        "description": article["description"]
    })

import pandas as pd
df = pd.DataFrame(articles)

df.head()

,title,source,published,description
0,Apple's Impressive Barcelona Store Reopens Nex...,MacRumors,2026-04-06T16:46:45Z,Apple's beautiful Passeig de Gràcia store in t...
1,Champions League Soccer: Stream Atlético Madri...,CNET,2026-04-14T16:01:17Z,Hansi Flick's team needs to overturn a two-goa...
2,Defending champion Alcaraz to miss French Open,BBC News,2026-04-24T16:02:16Z,Two-time defending champion Carlos Alcaraz say...
3,Lewandowski misses out on World Cup - who else...,BBC News,2026-03-31T22:41:01Z,"The World Cup includes 48 nations, but there a..."
4,Former BOA and Wada executive Reedie dies aged 84,BBC News,2026-04-06T17:24:23Z,"Sir Craig Reedie, the former chair of the Brit..."

In [2]:
from sqlalchemy import create_engine

username = "postgres"
password = "libertycity"
host = "localhost"
port = "5432"
database = "dogs_db"

engine = create_engine(f"postgresql://{username}:{password}@{host}:{port}/{database}")

In [3]:
engine = create_engine("postgresql://postgres:libertycity@localhost:5432/news_db")

In [5]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\khana\anaconda3\lib\site-packages (2.9.12)

In [10]:
df.to_sql(
    name="news",
    con=engine,
    if_exists="replace",  # use "append" later
    index=False
)

9

In [11]:
import pandas as pd

pd.read_sql("SELECT * FROM news LIMIT 5;", engine)

,title,source,published,description
0,Apple's Impressive Barcelona Store Reopens Nex...,MacRumors,2026-04-06T16:46:45Z,Apple's beautiful Passeig de Gràcia store in t...
1,Champions League Soccer: Stream Atlético Madri...,CNET,2026-04-14T16:01:17Z,Hansi Flick's team needs to overturn a two-goa...
2,Defending champion Alcaraz to miss French Open,BBC News,2026-04-24T16:02:16Z,Two-time defending champion Carlos Alcaraz say...
3,Lewandowski misses out on World Cup - who else...,BBC News,2026-03-31T22:41:01Z,"The World Cup includes 48 nations, but there a..."
4,Former BOA and Wada executive Reedie dies aged 84,BBC News,2026-04-06T17:24:23Z,"Sir Craig Reedie, the former chair of the Brit..."